services:
  prometheus:
    image: prom/prometheus:v2.53.3
    container_name: remas-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data/data:/prometheus
    networks:
      - remas
      - vm_pass_thru
    restart: unless-stopped
  
  prometheus-process-exporter:
    image: ncabatoff/process-exporter:sha-b2740a6
    container_name: remas-prometheus-process-exporter
    ports:
      - "127.0.0.1:9256:9256"
    volumes:
      - /proc:/host/proc:ro
      - ./prometheus/process-exporter-config/process-exporter-config.yml:/config/process-exporter-config.yml
    command: --procfs /host/proc -config.path /config/process-exporter-config.yml
    networks:
      - remas
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: remas-postgres
    environment:
      POSTGRES_USER: remas_main
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: remas_main_db
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - remas
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:11.5.2
    container_name: remas-grafana
    environment:
      GF_SMTP_ENABLED: ${SMTP_ENABLED}
      GF_SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
      GF_SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      GF_SMTP_USER: ${SMTP_USER}
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_HOST: "${SMTP_HOST}:${SMTP_PORT}"
      GF_SMTP_SKIP_VERIFY: ${SMTP_SKIP_TLS_VERIFICATION}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana
    networks:
      - remas
    restart: unless-stopped

networks:
  remas:
  # pass-thru to virtual machine network used by KVM
  vm_pass_thru:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.122.0/24
          ip_range: 192.168.122.16/28
          gateway: 192.168.122.1
    driver_opts:
      parent: virbr0
