services:
  prometheus:
    image: prom/prometheus:v2.53.3
    container_name: remas-prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data/data:/prometheus
    networks:
      - remas
      - vm_pass_thru
    restart: no

# Prometheus exporters for localhost - useful for testing
#  prometheus-process-exporter:
#    image: ncabatoff/process-exporter:sha-b2740a6
#    container_name: remas-prometheus-process-exporter
#    pid: host
#    ports:
#      - "127.0.0.1:9256:9256"
#    volumes:
#      - /proc:/host/proc:ro
#      - ./prometheus/process-exporter-config/process-exporter-config.yml:/config/process-exporter-config.yml
#    command: --procfs /host/proc -config.path /config/process-exporter-config.yml
#    networks:
#      - remas
#    restart: no
#
#  prometheus-node-exporter:
#    image: prom/node-exporter:v1.9.0
#    container_name: remas-prometheus-node-exporter
#    pid: host
#    ports:
#      - "127.0.0.1:9100:9100"
#    volumes:
#      - /:/rootfs:ro,rslave
#    command: --path.rootfs /rootfs
#    networks:
#      # For simplicity the same docker network is used as for other services.
#      # On real monitored nodes network should be set to 'host' to be able to
#      # monitor the node itself ('--network host' for docker run command or
#      # 'network_mode: host' option for docker compose).
#      - remas
#    restart: no

  postgres:
    image: postgres:17
    container_name: remas-postgres
    environment:
      POSTGRES_USER: remas_main
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: remas_main_db
    volumes:
      - ./postgres-data/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:15432:5432"
    networks:
      - remas
    restart: no

  grafana:
    image: grafana/grafana-oss:11.5.2
    container_name: remas-grafana
    environment:
      GF_SMTP_ENABLED: ${SMTP_ENABLED}
      GF_SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
      GF_SMTP_FROM_NAME: ${SMTP_FROM_NAME}
      GF_SMTP_USER: ${SMTP_USER}
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_HOST: "${SMTP_HOST}:${SMTP_PORT}"
      GF_SMTP_SKIP_VERIFY: ${SMTP_SKIP_TLS_VERIFICATION}
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana-data/data:/var/lib/grafana
    networks:
      - remas
    restart: no

networks:
  remas:
  # pass-thru to virtual machine network used by KVM
  vm_pass_thru:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.122.0/24
          ip_range: 192.168.122.16/28
          gateway: 192.168.122.1
    driver_opts:
      parent: virbr0
