global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
runtime:
  gogc: 75
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    http_headers: null
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  http_headers: null
  static_configs:
  - targets:
    - localhost:9090

- job_name: process_exporter_localhost
  static_configs:
  - targets: ['remas-prometheus-process-exporter:9256']
    labels:
      group: localhost
- job_name: process_exporter_test_node
  static_configs:
  - targets: ['192.168.122.84:9256']
    labels:
      group: test-node

- job_name: node_exporter_localhost
  static_configs:
  - targets: ['remas-prometheus-node-exporter:9100']
    labels:
      group: localhost
- job_name: node_exporter_test_node
  static_configs:
  - targets: ['192.168.122.84:9100']
    labels:
      group: test-node
